### ISSUE TITLE
open source time

### ISSUE THREAD

**Issue by FudongGe** [songw-zju/LiDAR2Map#1]
When will the code be open source please?

**Comment by songw-zju** [comment]
Hi @FudongGe, thanks for your interest. We're planning to release the code and models during the conference. If you have any questions, feel free to drop me an email.

**Comment by haoshuai714** [comment]
When will the code be open source please?

**Comment by songw-zju** [comment]
Sorry for the late reply. I've been busy with other projects lately and haven't updated them in a timely manner. I upload a preliminary code in the `dev` branch, but there are still some environmental conflicts that haven't been resolved well. You can take a look at some of the modules first. If you have any problems,  feel free to drop me an email.

**Comment by FudongGe** [comment]
> Sorry for the late reply. I've been busy with other projects lately and haven't updated them in a timely manner. I upload a preliminary code in the branch, but there are still some environmental conflicts that haven't been resolved well. You can take a look at some of the modules first. If you have any problems, feel free to drop me an email.`dev`

Thanks for your quick response. And I have a question. In your paper, does the term 'online' imply that the teacher model and the student model are trained simultaneously, instead of following the conventional distillation approach where a teacher model is pre-trained and then used to guide the student model? Based on the preliminary code you provided, this is how I understand it.
