### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by FudongGe** [songw-zju/LiDAR2Map#5]
Dear Song,

Thanks for your excellent work! And could you explain how long it takes to train an epoch and the corresponding batch size, equipment and so on?

Thanks for your attention.

**Comment by songw-zju** [comment]
Hi @FudongGe. I trained LiDAR2Map with 4 Telas V100 GPUs and the batch size was set to 4/6 per gpu. The total training process with 30 epochs took nearly one day to finish.
