### ISSUE TITLE
GPU memory usage

### ISSUE THREAD

**Issue by 248msc** [songw-zju/LiDAR2Map#8]
Thanks for sharing your work. May I know how much memory usage the model use? I tried setting num of workers to 1 and minimal batch_size. Still run out of memory on my 2080Ti (10.75GiB usable)

**Comment by songw-zju** [comment]
Thanks for your interest. The model is trained on four Telas V100 GPUs (32GB) and the batch size is set to 4/6 per gpu. With 2080Ti, you can consider reducing the batch size and image resolution.

**Comment by 248msc** [comment]
thanks. got it running with 3090, used around 16GB of gpu ram.
